### ISSUE TITLE
ids:DataResource mapped to owl:Thing

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/IDS-VocabularyProvider#5]
I have added the MobiDS vocabulary

https://github.com/Fraunhofer-IVI/Datenraum-Mobilitaet/blob/main/ontology/MobiDS-Ontology.ttl

to the Vocabulary Provider. The MobiDS vocabulary defines **transportMode** as a property of Datasource:
```
@prefix ids: <https://w3id.org/idsa/core/> .
...
mobids:transportMode a owl:ObjectProperty ;
  rdfs:domain ids:DataResource ;
  rdfs:range mobids:TransportMode ;
  rdfs:label "transport mode"@en .
```
But in the Vocabulary Provider it is displayed as a property of **Thing** (see picture below). This is wrong, since the MobiDS vocabulary does not state that every **Thing** can have a **transportMode**.

![grafik](https://user-images.githubusercontent.com/4161673/184310276-b4199ae2-4ebf-49c2-afb0-a627f29ddd15.png)

**Comment by waleedshabbir1** [comment]
@sebplorenz I just checked it seems like the problem is with the tool OWL2VOWL. 
We use this tool to convert ontology into .json file, and the generated JSON file doesn't have "DataResource" in it. 
I also tried running it separately with OWL2VOWL.jar file, and the problem is consistent

Maybe its best to open an issue with them 
[OWL2VOWL](https://github.com/VisualDataWeb/OWL2VOWL)
